### ISSUE TITLE
无法使用socks代理

### ISSUE THREAD

**Issue by Kid1010P** [Rvn0xsy/goDomain#1]
我使用Proxychains代理该项目，但其不工作在kali上.

**Comment by xirotech** [comment]
建議支持SSL 636

**Comment by Rvn0xsy** [comment]
> 建議支持SSL 636

已经更新，支持TLS连接方式
https://github.com/Rvn0xsy/goDomain/releases

**Comment by xirotech** [comment]
> 已经更新，支持TLS连接方式 https://github.com/Rvn0xsy/goDomain/releases

測試完美，Good Job👍

**Comment by Rvn0xsy** [comment]
> 我使用Proxychains代理该项目，但其不工作在kali上.

proxychains hooks to dynamically loaded libc.

1. go doesn't even use libc, it uses its own syscall wrappers
2. go doesn't use dynamic linking, it uses static linking

https://github.com/rofl0r/proxychains-ng/issues/199

你可以使用[graftcp](https://github.com/hmgle/graftcp)进行代理
